# Copyright (c) 2021, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
---
name: Oracle Cloud Infrastructure CLI Action
description: Run an Oracle Cloud Infrastructure (OCI) CLI command.
inputs:
  command:
    description: >-
      The command and arguments to provide to the "oci" tool. Most commands
      specify a service, followed by a resource type and then an action,
      e.g. "iam user list --compartment-id <compartment-ocid>"
    required: true
  query:
    description: >-
      (Optional) JMESPath query [http://jmespath.org/] to run on the response
      JSON before output.
    required: false
    default: ''
  region:
    description: >-
      (Optional) The region against which to make calls. Defaults to the region
      specified in the oracle-actions/configure-oci-credentials.
    required: false
    default: ''
  silent:
    description: >-
      (Default: false) If set to False, will stream the output of the command
      directly to the log. This may leak confidential information. We
      recomment keep this as false except for debugging purposes.
    required: false
    default: true
outputs:
  output:
    description: Response output in JSON format
  raw_output:
    description: >-
      If the output of a given query is a single string value, this will return
      the string without surrounding quotes.
runs:
  using: 'node12'
  main: 'dist/index.js'
