name: Sanity test of run-oci-cli-command

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: Sanity test run-oci-cli-command action
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:
      - uses: actions/checkout@v4

      - name: Check for OCI CLI environment variables
        run: |
          env | grep OCI_CLI

      - name: Get IAM region list
        id: test-action-iam-region-list
        uses: ./
        with:
          command: iam region list
          silent: false

      - name: Echo IAM region list
        id: echo-os-ns-get
        run: |
          echo "Output: ${{ steps.test-action-iam-region-list.outputs.output}}"
          echo "Raw output: ${{ steps.test-action-iam-region-list.outputs.raw_output}}"

      - name: Test non-JSON output
        id: test-non-json-output
        uses: ./
        with:
          command: --output=table iam region list
          silent: false
